### ISSUE TITLE
JSON upload errors

### ISSUE THREAD

**Issue by wernersun** [vkuznet/ChessDataManagement#2]
@vkuznet: I am attempting to upload the following json using the web interface:
```
[wms8@lnx201 metadata]$ cat common-example1.json
{
    "Facility":"CHESS",
    "Cycle":"[2022-3]",
    "PI":"Sun",
    "BTR":"sun-002",
    "Beamline":["2A"],
    "StaffScientist":"Pollock",
    "BeamlineFundingPartner":["CHEXS_NSF"],
    "Alignment":false,
    "DataLocationRaw":"/nfs/chess/raw/test-download",
    "CESRCondtions":["21BunchMode"],
    "Detectors":["Vortex"],
    "ExperimentType":["Spectroscopy"],
    "Technique":["DiffuseScattering"],
    "SampleType":["sample+can"],
    "SampleName":"ti7",
    "Calibration":false
}
```
but I receive an error saying
```
Api web processing error: Unable to find schema for this records <schema /mnt/chessdata/web/schemas/common.json, map 21 entries>, error=record key 'user' is not known
```
which is puzzling because 'user' is not a key in the json file or in the schema file web/schemas/common.json (88711a6).

I also tried using the CLI unsuccessfully:
```
[wms8@lnx201 metadata]$ /nfs/chess/sw/chessdata/chess_client -krbFile krb5_ccache -insert common-example1.json
<!DOCTYPE HTML>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head profile="http://www.w3.org/2005/11/profile">
    <title>CHESS Data Management System</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="en-us" />
    <meta http-equiv="Content-Script-Type" content="text/javascript" />
    <meta http-equiv="imagetoolbar" content="no" />
    <meta name="author" content="Valentin Kuznetsov (vkuznet at gmail dot com)" />
    <meta name="MSSmartTagsPreventParsing" content="true" />
    <meta name="ROBOTS" content="ALL" />
    <meta name="Copyright" content="(CC) 2019, CHESS collaboration." />
    <meta name="Rating" content="General" />

    <link rel="stylesheet" type="text/css" href="/css/main.css"/>
    
    <link rel="stylesheet" href="/css/kube.min.css">

    <link rel="search" type="application/opensearchdescription+xml" href="/opensearch" title="CHESS Data Management System" />
    <script type="text/javascript" src="/js/prototype.js"></script>
    <script type="text/javascript" src="/js/utils.js"></script>
    <script type="text/javascript" src="/js/ajax_utils.js"></script>

</head>
<body class="yui-skin-sam">

<div id="banner" class="is-navbar-container">
    <div class="is-brand">
        <b class="is-logo">CHESS Data Management System</b>
    </div>
    <div class="is-navbar">
        
        <nav>
            <ul>
                <li><a id="web_top_home" href="/">Home</a></li>
                <li><a id="web_top_search" href="/search">Search</a></li>
                <li><a id="web_top_status" href="/status">Status</a></li>
                <li><a id="web_top_faq" href="/faq">FAQ</a></li>
                <li><a id="web_top_bug" href="https://github.com/vkuznet/ChessDataManagement/issues">Bug report</a></li>
            </ul>
        </nav>
        
        <nav class="is-push-right">
            <ul>
                
                
                <li><a href="javascript:deleteCookie('auth-session');load('/');">Logout</a></li>
            </ul>
        </nav>
    </div>
</div>


<div class="center-70 alert is-error is-large is-text-center">
UNABLE TO INSERT DATA
</div>

<br/>
<hr class="line" />
<div class="is-70 is-center is-small is-text-center">
    Copyright &#169; Cornell Laboratory for Accelerator-based Sciences and Education
    Supported by: <img src="/images/nsf_logo.png" alt="NSF" width="30">
</div>

</body>
</html>
```

**Comment by vkuznet** [comment]
Try to run through web form :)

There are few things which I added to the schema, and so far those are hidden input fields: User, Date, Description.
- The User is what is shown on web UI when you use your kerberos credentials, i.e. it is your user name
- the Date is UNIX timestamp
- the Description is what on web UI is shown as "Beamline Notes"

I think all of them are important, and should be part of the schema, because we need to keep track of how injected the data. I should adjust web upload form to add them, but for CLI we need to provide them.

Said that, we should discuss if we should include them as part of schema or keep them hidden and adjust code to add them automatically. I'm open for discussion.

Meanwhile, just add them in your JSON doc, like
```
"User":"Werner",
"Date": 1665787840,
"Description": "bla"
```

**Comment by wernersun** [comment]
Unfortunately, I added the hidden fields, but I still get the same errors, both in the web upload form and the CLI. I even tried adding "SchemaName" (which I found in web/schema.go), but no luck....
```
{
    "Facility":"CHESS",
    "Cycle":"[2022-3]",
    "PI":"Sun",
    "BTR":"sun-002",
    "Beamline":["2A"],
    "StaffScientist":"Pollock",
    "BeamlineFundingPartner":["CHEXS_NSF"],
    "Alignment":false,
    "DataLocationRaw":"/nfs/chess/raw/test-download",
    "CESRCondtions":["21BunchMode"],
    "Detectors":["Vortex"],
    "ExperimentType":["Spectroscopy"],
    "Technique":["DiffuseScattering"],
    "SampleType":["sample+can"],
    "SampleName":"ti7",
    "Calibration":false,
    "User":"Werner",
    "Date": 1665787840,
    "Description": "bla",
    "SchemaName": "common"
}
```

**Comment by vkuznet** [comment]
ok, fixed in b050868, service is restarted, please try again and if it works you may close the issue. The `SchemaName` should not be required in web UI forms as it is read internally form the page, but we'll need it to integrate on CLI (I thought to make an extra option though instead of being part of JSON doc, but we will discuss it later).

**Comment by wernersun** [comment]
Thanks, I am now able to upload a JSON using both the web form and CLI. However, I found that if I upload a second (different) JSON, it overwrites the first record instead of creating a new one. I.e. the uploaded records all keep the same "_id" values, but they have different "did" values.

For example, after the first JSON upload, I searched with
```
/nfs/chess/sw/chessdata/chess_client -query="pi:sun" -krbFile krb5_ccache
```
and got 2 records, the last one being:
```
{"_id":"634ad32d6768e89e30b04cb1","alignment":false,"beamline":["2a"],"beamlinefundingpartner":["chexs_nsf"],"btr":"sun-002","calibration":false,"cesrcondtions":["21bunchmode"],"cycle":"[2022-3]","datalocationraw":"/nfs/chess/raw/test-download","dataset":"/chess/ti7/vortex","date":1665787840,"description":"bla","detectors":["vortex"],"did":1665848109190538731,"experimenttype":["spectroscopy"],"facility":"chess","path":"/nfs/chess/raw/test-download","pi":"sun","samplename":"ti7","sampletype":["sample+can"],"schemaname":"common","staffscientist":"pollock","technique":["diffusescattering"],"user":"werner"}
```
After a second JSON upload, I **still** get 2 records, and the last one has the same "_id" as before, but with updated fields (including "did"):
```
{"_id":"634ad32d6768e89e30b04cb1","alignment":true,"beamline":["3a"],"beamlinefundingpartner":["chexs_nsf"],"btr":"sun-003","calibration":true,"cesrcondtions":["21bunchmode"],"cycle":"[2022-3]","datalocationraw":"/nfs/chess/raw/test-download","dataset":"/chess/ti7/vortex","date":1665787850,"description":"bla","detectors":["vortex"],"did":1665849341783758720,"experimenttype":["spectroscopy"],"facility":"chess","path":"/nfs/chess/raw/test-download","pi":"sun","samplename":"ti7","sampletype":["sample+can"],"staffscientist":"pollock","technique":["diffusescattering"],"user":"werner"}
```
This does not happen with manual entry on the web form -- each submission generates a new record, as expected.

**Comment by vkuznet** [comment]
Werner, this is internal logic I originally put it. It is based on `dataset` of the record, where `dataset` is defined as a path of three attributes `dataset=/<Facility>/<SampleName>/<Detectors>`. If this path is identical the record should be updated. Since now we reach the level of functionality that records are successfully processed we should discuss logic of how we will store records. I can adjust code to whatever logic you will desire but I do not know a-pirory what is this functionality, and I used `dataset` path logic since we have similar in CMS. Said that, what I need from you know is the following:
- define logic of data insertion and outline all steps, e.g. you may say that regardless of who inject data all data are unique and should be inserted individually, or you may say if certain attribute(s) is identical in what we have in MetaData we will update the record
- provide me example records to satisfy your logic above

Once, I'll have that I can adjust code accordingly. But so far the main functionality is working and in fact I'm glad that you are able to search for records. So we are moving forward.

**Comment by vkuznet** [comment]
btw, the records you posted have different btr values (not only did's).

**Comment by wernersun** [comment]
Thanks for the explanation, Valentin. Yes, I expected every injection to generate a new record -- that's why the two records have several values that are different. I can confirm that uploading a json with a different dataset results in a new record -- mystery solved!

Do you have any documentation about the logic that is currently implemented?

**Comment by vkuznet** [comment]
Werner, there is no yet documentation since we still in a process of defining how service should work but here is how you should navigate through the code:
- each HTTP request goes to a specific end-point (the URL path), see https://github.com/vkuznet/ChessDataManagement/blob/master/web/handlers.go#L73-L94
- then you can see which HTTP handler is used to process the request, e.g. DataHandler is default one https://github.com/vkuznet/ChessDataManagement/blob/master/web/handlers.go#L93 which takes HTTP request from web form and process it via `ProcessHandler`, see https://github.com/vkuznet/ChessDataManagement/blob/b050868b28025e06a6ba4220d9fddc4edb91d05d/web/handlers.go#L599
- within `ProcessHandler`  we call `insertData` API, see https://github.com/vkuznet/ChessDataManagement/blob/b050868b28025e06a6ba4220d9fddc4edb91d05d/web/helpers.go#L171 which by itself make a DB call, e.g. `MongoUpsert` https://github.com/vkuznet/ChessDataManagement/blob/b050868b28025e06a6ba4220d9fddc4edb91d05d/web/helpers.go#L222

The `insertData` API is where the logic is. In particular on line https://github.com/vkuznet/ChessDataManagement/blob/b050868b28025e06a6ba4220d9fddc4edb91d05d/web/helpers.go#L209 you see how I define internal `dataset` which is composed by three parts which represent unique record. This where the changes will go once we define the logic.

**Comment by vkuznet** [comment]
@wernersun , did you read the code? Do you need anything else here?

**Comment by wernersun** [comment]
@vkuznet, thanks for the pointers. I did read the code, and I still have questions, but it's probably easier to discuss in real-time.
