### ISSUE TITLE
error when submitting ID3A metadata via web

### ISSUE THREAD

**Issue by ksg52** [vkuznet/ChessDataManagement#7]
@vkuznet I get the following error:
'''
Web processing error: Unable to find schema for this records <schema /mnt/chessdata/web/schemas/ID3A.json, map 60 entries>, error=invalid data type for key=ReferenceEnergyScanNumber, value=0, type=int, expect=int32 <schema /mnt/chessdata/web/schemas/ID4B.json, map 47 entries>, error=record key 'GuardSlitHorizontalSize' is not known <schema /mnt/chessdata/web/schemas/lite.json, map 21 entries>, error=record key 'EnergyScan' is not known <schema /mnt/chessdata/web/schemas/ID1A3.json, map 41 entries>, error=record key 'EnergyFoil' is not known
'''
when I did the following:
- populate fields using the ID3A schema on the webform
- confirm all required fields are populated
- hit "submit"

**Comment by vkuznet** [comment]
@wernersun , please commit ID3A.json file into repo and make sure that you check `ReferenceEnergyScanNumber` type according to the error it should be int32. I may either cast int type to int32 or we should have int32 in a schema. I can debug this once I'll get json schema file in place.

**Comment by wernersun** [comment]
@vkuznet: PR created https://github.com/vkuznet/ChessDataManagement/pull/8

**Comment by vkuznet** [comment]
@ksg52 , please try again the issue should be fixed now.

@wernersun , please check **ALL** schemas as they contains plenty of errors. While I was debugging this issue I found at least three different issues with ID3A schema, please see my commits:
- wrong type name, https://github.com/vkuznet/ChessDataManagement/commit/d207b7f76b35a1fb23f99144f2554f99c63f3262
- wrong type, https://github.com/vkuznet/ChessDataManagement/commit/6fb4b0e2d2080de7285f67adfa9d13a0d0a34817
- improper values for given type, e.g. if type is bool, then values should not contain list of strings (which looks like bool values), see https://github.com/vkuznet/ChessDataManagement/commit/0f00fa4ef3e48f7673da04f88a7563367d893864

Please do your home work of validating every aspect of the schema as debugging takes lots of time and I should not waste my type on mistakes which exists because you do not validate your schema.

So far, I'm closing this ticket as resolved. If you'll find new issue please open new ticket.

**Comment by wernersun** [comment]
Thanks, Valentin. Sorry about the schema errors. Adding @kenygren, since the schemas were generated by the python script.

Regarding the bools, that is related to the question we discussed yesterday, for which I will open a separate issue.

**Comment by vkuznet** [comment]
The bool in dropdown is fixed too, i.e. default is not selected and if it is
mandatory key then web form will complain if user will not make a selection.
Just try it out before opening the ticket.
